### ISSUE TITLE
Add Observations 

### ISSUE THREAD

**Issue by aaronspring** [ecmwf-lab/climetlab-s2s-ai-challenge#2]
I understood that you would also add observations on EWC. @floriankrb 

Here are my scripts https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/blob/master/notebooks/download_verification_data.ipynb

regarding the naming discussion we had with Frederic about 2t or t2m, we have to make sure that the observations have the same variable name and unit. In my example not yet done. 

currently IRI CPC temp is in C, but ECMWF is in K. If you want to put IRI data into ECMWF cloud, I started notebooks for renku here

**Comment by floriankrb** [comment]
Closing as issues are tracked at :
https://renkulab.io/gitlab/aaron.spring/s2s-ai-challenge/-/issues  (general)
https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/issues (internal to S2S challenge organisers)
