### ISSUE TITLE
Add recalibrated benchmark ECMWF real-time forecast 2020

### ISSUE THREAD

**Issue by aaronspring** [ecmwf-lab/climetlab-s2s-ai-challenge#3]
along the same lines as #2:
- Will ECMWF provide this recalibrated real-time forecasts on EWC?
- If so, would the code for that be also shared somewhere in this repo?

**Comment by floriankrb** [comment]
Yes, ECMWF can host the observation data and the recalibrated data, (and the tercile data) at the same place (S3 bucket wit https access).

**Comment by floriankrb** [comment]
The code to build the data should not be shipped to the end-user. It cannot got to the climetlab-s2s-ai-challenge/ directory in the present repos.
But some part of it may something you want to give them (tools to compute a tercile, tricky monthly average with leap year, etc.). IMHO, this code should go in the climetlab-s2s-ai-challenge/ directory.

I see to proper locations for the databuilding code :
- Another repos. Perhaps in https://github.com/ecmwf-lab/dev-climetlab-s2s-ai-challenge/ or the one in renkulab ? This new repos should have the present one as a dependency.
- Another folder in this repos which will not be zipped when releasing to pypi. For instance ./building_data/ ?

**Comment by aaronspring** [comment]
> The code to build the data should not be shipped to the end-user.

Why shouldn’t it?

**Comment by aaronspring** [comment]
The code could also just be in the renku repo. But if it’s hosted here, why not have it as an explanation here?

My question furthermore is about how to compute this recalibration. A simple way https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/blob/master/notebooks/bias_reduction_forecast.ipynb from me but probably you at ECMWF have better codes for that.

**Comment by floriankrb** [comment]
We discussed with Frederic, he will recompute it and I will upload the data (same GRIB+netcdf, maybe zarr) formats.
Since we have two benchmarks now, I suggest we name them as:
- forecast-benchmark-ml : the benchmark using the quick ML model trained by Aaron (was previously forecast-benchmark)
- forecast-benchmark-recalibrated : this recalibrated data.

Latter on, we will open-source the appropriate code (likely to by python) to compute this recalibrated data.

**Comment by aaronspring** [comment]
I would skip that:
> forecast-benchmark-ml : the benchmark using the quick ML model trained by Aaron (was previously forecast-benchmark)

I was just playing around with the data and keras, and the time alignment was very slopping and actually only really computed for one step.

I think `forecast-benchmark` as recalibrated ECMWF is enough.

**Comment by floriankrb** [comment]
ok

**Comment by floriankrb** [comment]
Closing as issues are tracked at :
https://renkulab.io/gitlab/aaron.spring/s2s-ai-challenge/-/issues  (general)
https://renkulab.io/gitlab/aaron.spring/s2s-ai-competition-bootstrap/-/issues (internal to S2S challenge organisers)
