### ISSUE TITLE
Size of data 

### ISSUE THREAD

**Issue by GaelKBertrand** [ecmwf-lab/climetlab-s2s-ai-challenge#33]
I would like to have  a general idea on the size of data before using it. How big is the data from climatelab?

**Comment by aaronspring** [comment]
depends on which models and variables you want to access.

see the file sizes: 

- https://storage.ecmwf.europeanweather.cloud/s2s-ai-challenge/data/training-input/0.3.0/netcdf/index.html
- https://storage.ecmwf.europeanweather.cloud/s2s-ai-challenge/data/test-input/0.3.0/netcdf/index.html
