### ISSUE TITLE
test notebooks in CI

### ISSUE THREAD

**Issue by aaronspring** [ecmwf-lab/climetlab-s2s-ai-challenge#4]
transfered from https://github.com/ecmwf-lab/climetlab-s2s-ai-competition/pull/11

I want to emphasise that I think it is important to test the notebooks and netcdf and grib functionality. Is not needed on all data but at least that notebooks and basic functionality is working @b8raoult @floriankrb. Long times to complete reflect the user experience.

**Comment by floriankrb** [comment]
I agree, regarding the download speed, the issue is open on https://jira.ecmwf.int/browse/SD-47465 (not sure if you have access to this). We may need to set up a nginx proxy on the EWC to bypass the load balancer restrictions.

**Comment by floriankrb** [comment]
Added testing for basic functionalities for grib and netcdf. Runs ok  with github actions. It still uses the '-dev' datasets which are smaller and which are different from the actual ones to speed up the test (speed download is a different issue that should be tracked elsewhere).
